In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3463, 4279, 4513, 557],
 [3463, 4279, 4513, 1253],
 [3463, 9169, 4513, 9508],
 [1705, 86, 2396, 4962, 8209],
 [1705, 86, 2396, 4962, 9661],
 [9913, 3463, 3117, 4513, 7524],
 [5166, 5050, 7059, 4962]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3463 4279 4513  557]
 [   0    0    0    0 3463 4279 4513 1253]
 [   0    0    0    0 3463 9169 4513 9508]
 [   0    0    0 1705   86 2396 4962 8209]
 [   0    0    0 1705   86 2396 4962 9661]
 [   0    0    0 9913 3463 3117 4513 7524]
 [   0    0    0    0 5166 5050 7059 4962]]


In [8]:
##feature representation
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-07-06 09:19:40.267810: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2025-07-06 09:19:40.268090: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-07-06 09:19:40.268439: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-07-06 09:19:40.268528: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-07-06 09:19:40.268917: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

2025-07-06 09:20:15.444022: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 360ms/step


array([[[ 0.03931577,  0.04181551,  0.01533273, -0.01278663,
         -0.02705759,  0.03774322,  0.040566  , -0.00046695,
          0.0440443 ,  0.00211927],
        [ 0.03931577,  0.04181551,  0.01533273, -0.01278663,
         -0.02705759,  0.03774322,  0.040566  , -0.00046695,
          0.0440443 ,  0.00211927],
        [ 0.03931577,  0.04181551,  0.01533273, -0.01278663,
         -0.02705759,  0.03774322,  0.040566  , -0.00046695,
          0.0440443 ,  0.00211927],
        [ 0.03931577,  0.04181551,  0.01533273, -0.01278663,
         -0.02705759,  0.03774322,  0.040566  , -0.00046695,
          0.0440443 ,  0.00211927],
        [ 0.03349153, -0.01300304,  0.00460831, -0.01255677,
         -0.03956991,  0.01789999, -0.00786029, -0.03474923,
          0.03305036, -0.04174823],
        [ 0.00640114, -0.04239815, -0.03820618,  0.0080909 ,
         -0.0426042 ,  0.01724899, -0.01095019, -0.01762992,
         -0.00191407,  0.04908678],
        [ 0.00306104,  0.01093751,  0.03709597,  0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 3463, 4279, 4513,  557], dtype=int32)